#### Problem Statement 1: 
Write a function so that the columns of the output matrix are powers of the input vector. 

The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 

HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 

In [1]:
# Defining the function

import numpy as np

def ATV_func (arr, N):
    return (np.vstack ([arr**(N-i-1) for i in range (N)]).transpose ())

In [2]:
# Using the function on an array

array = np.array ([1,4,7,4])
ATV_func (array, 3)

array([[ 1,  1,  1],
       [16,  4,  1],
       [49,  7,  1],
       [16,  4,  1]], dtype=int32)

In [3]:
# Verifying the result using the numpy function vander

np.vander (array, 3)

array([[ 1,  1,  1],
       [16,  4,  1],
       [49,  7,  1],
       [16,  4,  1]])

In [4]:
# Trying with another array

array = np.array ([2,6,4,9])
print ('The results from self defined function =\n', ATV_func (array,4))
print ('\nThe results from numpy function =\n', np.vander (array,4))

The results from self defined function =
 [[  8   4   2   1]
 [216  36   6   1]
 [ 64  16   4   1]
 [729  81   9   1]]

The results from numpy function =
 [[  8   4   2   1]
 [216  36   6   1]
 [ 64  16   4   1]
 [729  81   9   1]]


#### Problem Statement 2:
Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [5]:
# Defining the function

def mov_avg (lst, k) :
    return (np.round ([np.mean (lst [i : i + k]) for i in range (len (lst) - k + 1)],2))

In [6]:
lst_num = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print ('The list of numbers =', lst_num, '\nwindow = 3')
print ('The moving average of the list of numbers with window = 3 is\n', mov_avg (lst_num, 3))

The list of numbers = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
window = 3
The moving average of the list of numbers with window = 3 is
 [  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]


##### Prepared by Sahaj Harnal
##### Email: sahaj.harnal@gmail.com